### ISSUE TITLE
decodeCertificate throws IllegalArgumentException on an unparseable certificate

### ISSUE THREAD

**Issue by scantor** [vt-middleware/cryptacular#16]
The org.cryptacular.util.CertUtil.decodeCertificate(byte[]) method catches the Java runtime's CertificateException when there's a problem parsing a certificate, and turns it into an IllegalArgumentException. That obviously isn't declared on the method since it's a runtime exception, so we weren't catching that in our X509Support class in OpenSAML.

I'd say as a general matter the parsing oriented methods ought to avoid throwing runtime errors since those are certainly likely to show up at runtime through no fault of the code.

**Comment by serac** [comment]
Fixed in the context of pull request #22.
