### ISSUE TITLE
CipherBean impl that uses asymmetric keys

### ISSUE THREAD

**Issue by mmoayyed** [vt-middleware/cryptacular#17]
Per the discussion here:
https://github.com/Jasig/cas/pull/843#discussion_r25959862

**Comment by dfish3r** [comment]
Using a bean impl for asymmetric keys probably isn't a good idea. It could only be safely used to encrypt the number of bits corresponding to its' key size. That sort of short lifespan doesn't mesh well with typically bean usage patterns.

Probably a moot point since this is such an old request.
