### ISSUE TITLE
KeyPairUtil and Closing InputStreams

### ISSUE THREAD

**Issue by rodwiddowson** [vt-middleware/cryptacular#24]
By Observation readPrivateKey and readPublicKey do *not* close the inputStream that they consume.  

+ Is this likely to always be the case and if so
+ Can this be documented in the Javadoc so that programmers know where they stand?

Thanks

**Comment by dfish3r** [comment]
I believe we followed the "he who opens it, closes it" philosophy.

We'll get that documented for the next release.

**Comment by dfish3r** [comment]
I'm not sure what I was originally thinking. Careful review indicates that supplied InputStreams are in fact closed. I added a unit test to confirm that behavior.

**Comment by serac** [comment]
I believe we can close this now. Sound good @rodwiddowson ?

**Comment by rodwiddowson** [comment]
Oh yes.
