### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [vt-middleware/cryptacular#25]
Hi:
The license files states:
```
This product is dual licensed under both the Apache2 and LGPL licenses.
See LICENSE-apache2 and LICENSE-lgpl.
```
Does this mean both apply? or that this is a choice of one or the other?

**Comment by dfish3r** [comment]
The licenses are mutually exclusive, so you'll have to pick which one you're going to use.

**Comment by pombredanne** [comment]
@dfish3r Thanks for the quick answer!
