### ISSUE TITLE
ASN.1 parsing broken with BC 1.54

### ISSUE THREAD

**Issue by dfish3r** [vt-middleware/cryptacular#26]
Upgrading Bouncy Castle to version 1.54 produces test failures.
Specifically the ASN.1 parsing of certain keys no longer works.

Work should be done on the bc-1.54-upgrade branch.

**Comment by ememisya** [comment]
It looks like post 1.54 ASN1Primitive#fromByteArray expects only a single object in the stream given and nothing else.  Resolved at 916153d7500dff1f009d95f0dee896240d14e19d

**Comment by dfish3r** [comment]
Merged in #30.
