### ISSUE TITLE
Clarification on the license conditions

### ISSUE THREAD

**Issue by romayankin** [vt-middleware/cryptacular#46]
I can see you are saying that this library is "is dual licensed under both the Apache2 and LGPL licenses"

Usually when components are dual licensed that means that either one of the applicable licenses can be used, but you are using the word "AND" which could mean that obligations from both Apache 2.0 and LGPL  v3 are applied. 

Also can you please specify which version of LGPL is applicable? There are three different versions and.

I'm only saying v3 above because I can see it is included with other source code files

**Comment by dfish3r** [comment]
You can choose whether to use the Apache2 or LGPL license, not both.
The licenses are included with the project to avoid ambiguity.

**Comment by pombredanne** [comment]
@dfish3r It would be great to make this a tad more explicit by stating this an OR e.g. a choice rather than an AND e.g. both apply.

**Comment by dfish3r** [comment]
Please send me a PR that clarifies it for you. Clearly I'm not the best wordsmith ;)
