### ISSUE TITLE
Issue with AbstractOTPGenerator.truncate method in case of other digest than SHA1

### ISSUE THREAD

**Issue by bengri6** [vt-middleware/cryptacular#59]
Hello 

I found a bug when using SHA256 instead of SHA1 digest with the TOTPGenerator . The returned OTP are wrong. The issue is caused by a bug in the AbstractOTPGenerator.truncate method:

```
private int truncate(final byte[] hmac)
  {
    final int offset = hmac[19] & 0xf;
    return
      (hmac[offset] & 0x7f) << 24 |
      (hmac[offset + 1] & 0xff) << 16 |
      (hmac[offset + 2] & 0xff) << 8 |
      (hmac[offset + 3] & 0xff);
  }
```

The byte array in case of SHA256 is not 20 but 32 bytes.  The hardcoded value 19 should be replaced by  

`hmac.length - 1
`

something like this:
```
private int truncate(final byte[] hmac)
  {
    final int offset = hmac[hmac.length - 1] & 0xf;
    return
      (hmac[offset] & 0x7f) << 24 |
      (hmac[offset + 1] & 0xff) << 16 |
      (hmac[offset + 2] & 0xff) << 8 |
      (hmac[offset + 3] & 0xff);
  }
```
Thanks in advance for fixing this issue.

**Comment by serac** [comment]
Thanks for the report. I'll get on it shortly.

**Comment by dfish3r** [comment]
@bengri6 please confirm the fix in master and then I'll close.

**Comment by bengri6** [comment]
Hello
the fix is OK.
thanks a lot.

**Comment by dfish3r** [comment]
Fix confirmed by reporter.
