### ISSUE TITLE
BouncyCastle Maven artifact name changes

### ISSUE THREAD

**Issue by phax** [vt-middleware/cryptacular#61]
Hi guys,
BouncyCastle did change in its latest 1.71 release the naming of the Maven artefacts: 
Instead of `bc*-jdk15on.jar` they are now labeled `bc*-jdk18on.jar` and require Java 1.8 as the basline.

See https://www.bouncycastle.org/latest_releases.html for details:
> Packaging Change (users of 1.70 or earlier): BC 1.71 changed the jdk15on jars to jdk18on so the base has now moved to Java 8. For earlier JVMs, or containers/applications that cannot cope with multi-release jars, you should now use the jdk15to18 jars.

It would be great if you could adopt these changes in here and make a new release.

Thanks!

**Comment by dfish3r** [comment]
I believe what you're asking for happened in this commit: https://github.com/vt-middleware/cryptacular/commit/ae821d23f8e76ef50e57a1592a2d2def89a4eb8d

And was included in tag 1.2.5

Am I misunderstanding?

**Comment by phax** [comment]
Yes exactly - sorry to bother you.
I am just using cryptacular indirectly through wss4j and didn't check the latest POM.
Thanks for the swift response.
